### PR TITLE
improve change SSL certificate locations example

### PR DESCRIPTION
**Pull request by bbodenmiller**
* use an example that is not also the default location
* break in to its own section

### CODE REVIEW

**Comment by dosire** [comment]
@maxlazio What do you think? I'm not sure that breaking the header and changing the default of /etc/ssl is a good idea.

**Comment by bbodenmiller** [comment]
@dosire why's that? The header used to describe two unrelated topics. The example showed a location that is the default location - perpus is to show how to change from the default. If you are using the default location no need for the setting to be set. I'm just not a fan of showing an example that in practice you wouldn't need or use.

**Comment by axilleas** [comment]
I think @dosire 's concern is if the change of the header breaks any references in other places. Now that omnibus docs are in doc.gitlab.com we have to be extra careful.

In turn, I'm in favor of splitting it but also add everything related to SSL in the new section. Currently you can see under **Warning** how to configure SSL, not a very good place IMHO.

Also I would prefer to leave `/etc/gitlab/ssl` in the example as it is the recommended path and just add a note that this path is configurable and `/etc/gitlab/ssl` is just an example.

My 2c

**Comment by dosire** [comment]
@axilleas Exactly. Good idea to put everything SSL related in a new section. I'll leave it up to @maxlazio

**Comment by maxlazio** [comment]
@bbodenmiller Both @dosire and @axilleas are right. We are trying to maintain headers to not break any existing links. 

I'm not sure I like the change that switches `/etc/gitlab/` with `somewhere`. If a user 100% knows what they are doing they will know the best path for their system and they will ensure that they backup everything. Otherwise they might think twice why we are putting everything there and read other docs(most importantly, backup). Saying `/something` doesn't bring any value or improves the doc imo.

I like the idea of moving everything SSL related into a new section or even better, new document that will list all necessary settings to get SSL with GitLab. In that case we can just link to the new doc from the existing headers.

**Comment by bbodenmiller** [comment]
Alright - this is more work than it's worth to me. At a minimum I'd suggest updating the wording to inform the user that this is just an example and if you use the default location of `/etc/gitlab/ssl/` you do not need to apply the setting.

**Comment by axilleas** [comment]
@bbodenmiller thanks for the PR and sorry if that caused any trouble. I will try to update the docs based on everyone's suggestions.

**Comment by bbodenmiller** [comment]
No problem. I do think finding a way to automatically generate pages like http://doc.gitlab.com/omnibus/ based on the current headers would reduce some of the new friction to make changes to docs.

**Pull request closed without merging**
