### PR TITLE
add packages link to 6.6+ to 7.10+

### PR DESCRIPTION
**Pull request by bbodenmiller**
Improves upgrade details by stating where to get packages.

Replaces #23.

### CODE REVIEW

**Comment by dblessing** [comment]
If users install initially according to the directions on the website the package repo will be installed on their system. In this case the upgrade is simply 'yum update' or 'apt-get update'. No need to download the package manually. 

Which process should we document?

**Comment by bbodenmiller** [comment]
I realized this after I submitted this. I think we need to document both as not everyone can use the package repo due to security concerns. I vote we merge this as it improves current documented process and then a seperate MR for adding package repo upgrade details.

**Comment by maxlazio** [comment]
Why not improve it in one go?

**Comment by bbodenmiller** [comment]
@maxlazio if you have some exact wording you want me to throw in then sure. I however won't have a chance to think about it until next weekend at the earliest.

**Comment by maxlazio** [comment]
@bbodenmiller sadly I don't have enough time to think of something. These docs need improvement for sure and they need to favor installation using package repositories. I will merge this as it at least adds a link to the valid repos in case someone doesn't understand how to download a package.

**Pull request merged**
