### PR TITLE
Set database collation

### PR DESCRIPTION
**Pull request by bbodenmiller**
Set database collation to match upstream settings. Related to https://github.com/gitlabhq/gitlabhq/pull/8195.

### CODE REVIEW

**Comment by bbodenmiller** [comment]
@maxlazio squashed.

**Comment by axilleas** [comment]
@bbodenmiller would you be kind to also add this change in the template example?

https://github.com/gitlabhq/omnibus-gitlab/blob/master/files/gitlab-config-template/gitlab.rb.template#L206

**Comment by bbodenmiller** [comment]
@axilleas done.

**Comment by maxlazio** [comment]
@bbodenmiller Great, thanks :)

**Pull request merged**
