### PR TITLE
Bugfix for HTTP to HTTPS redirection: wrong variable was used

### PR DESCRIPTION
**Pull request by demofly**
Fixes an issue with broken project icons.

### CODE REVIEW

**Comment by maxlazio** [comment]
Can you explain what the problem was, how it manifested itself and how did your configuration look?
I am not sure if this PR is going to create more issues than resolve.

Current state of the nginx template is confusing, I understand this. Sadly we are trying to cover couple of different use cases and untangling that will be a long process.

**Comment by demofly** [comment]
In my case, with this configuration in `/etc/gitlab/gitlab.rb`:
```
################
# GitLab Nginx #
################
## see: https://gitlab.com/gitlab-org/omnibus-gitlab/tree/629def0a7a26e7c2326566f0758d4a27857b52a3/doc/settings/nginx.md

nginx['enable'] = true
nginx['port'] = 443
nginx['client_max_body_size'] = '250m'
nginx['redirect_http_to_https'] = true
nginx['redirect_http_to_https_port'] = 80
nginx['ssl_certificate']        = "/etc/nginx/ssl/gitlab.<mycompany>.com.crt"
nginx['ssl_certificate_key']    = "/etc/nginx/ssl/gitlab.<mycompany>.com.key"
nginx['ssl_ciphers'] = "ECDSA:ECDH+aRSA:DH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED"
nginx['ssl_prefer_server_ciphers'] = "on"
nginx['ssl_protocols'] = "TLSv1.2 TLSv1.1 TLSv1" # recommended by https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html & https://cipherli.st/
/http/ngx_http_ssl_module.html
nginx['listen_port'] = 443
nginx['listen_https'] = true
```
I'm getting the next misconfig in `/var/opt/gitlab/nginx/conf/gitlab-http.conf`:
```
server {
  listen *:80;
  server_name gitlab.<mycompany>.com;
  server_tokens off; ## Don't show the nginx version number, a security best practice
  return 301 https://gitlab.<mycompany>.com:80$request_uri;
  access_log  /var/log/gitlab/nginx/gitlab_access.log gitlab_access;
  error_log   /var/log/gitlab/nginx/gitlab_error.log;
}
```
Note that `https://gitlab.<mycompany>.com:80` is a fatal mess in 301 redirect. Your current template makes redirect to 80 HTTP port with `https://` prefix in the URL.

After you merge my fix, It will be `https://gitlab.<mycompany>.com:443` and all will be fine.

That is all about this merge request.

Additionally, you should review layout to find out why project icons have HTTP URLs insted HTTPS URLs even when the config is totally for HTTPS, however, it is out of the scope of this pull request.

====

Also, I recommend you to copy this preset for your samples in templates according to my PCI DSS compatible solution: 
```
nginx['ssl_ciphers'] = "ECDSA:ECDH+aRSA:DH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED"
```
Here is my a little bit old publication about it: http://wikilinux.vn/sslv3-design-vulnerabilities-and-a-new-recommended-nginx-ssl-configuration/

You can validate it with:
```
# openssl ciphers 'ECDSA:ECDH+aRSA:DH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED'
```

TLSv1 is not removed in my current config to mitigate compatibility issues with web hooks we are using (some clients are crappy old to support TLSv1.1 or TLSv1.2)

**Comment by demofly** [comment]
Also, note, the bug is reproduced in Gitlab v8.2.1 (a package for Debian jessie)

**Comment by maxlazio** [comment]
How does your `external_url` setting look?

**Comment by demofly** [comment]
```
external_url 'http://gitlab.<mycompany>.com'
```

**Comment by maxlazio** [comment]
Omnibus-gitlab package tries to be smart and parse the configuration in a way that will enable user to have minimum configuration. Since you've set your external url to http, the configuration will assume that you want to have GitLab reachable at that address. Since you are using mostly defaults, configuration that looks like:

```
external_url 'https://gitlab.<mycompany>.com'
nginx['redirect_http_to_https'] = true
nginx['ssl_ciphers'] = "ECDSA:ECDH+aRSA:DH:!aNULL:!eNULL:!MEDIUM:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SEED"
```

will be sufficient to get what you are trying to achieve.

external_url will be parsed and GitLab will recognise you are using https, set the port to 443 and redirect any http request to https.

**Comment by demofly** [comment]
Checked that carefully, the issue is went away after I've fixed `http://` prefix in `external_url`.

Sorry about my mistake. Thank you very much.

**Pull request closed without merging**
